'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
type Event = { event_type: string; product_slug?: string | null; occurred_at: string };
type Detail = { link: { id: string; recipient_label?: string | null; label?: string | null; target_type: string; product_slug?: string | null; total_opens: number; total_sessions: number; status: string; last_seen_at?: string | null; token: string }; events: Event[] };
export function SharedLinkDetail({ id }: { id: string }) {
  const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/catalog/links/${id}`).then((r) => r.json()).then((result) => setData({ ...result, events: result.events ?? [] } as Detail)).catch(() => setError('No pudimos cargar la actividad.')); }, [id]);
  if (error) return <p className="form-error">{error}</p>; if (!data) return <p className="muted">Cargando actividad…</p>;
  const { link, events } = data;
  async function toggle() { setBusy(true); const next = link.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'; await fetch(`/api/catalog/links/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: next }) }); setData({ link: { ...link, status: next }, events }); setBusy(false); }
  const products = events.filter((event) => event.event_type === 'PRODUCT_VIEWED' && event.product_slug).reduce<Record<string, number>>((acc, event) => { acc[event.product_slug!] = (acc[event.product_slug!] ?? 0) + 1; return acc; }, {});
  return <><Link className="back-link" href="/app/catalogo/compartidos">← Volver a compartidos</Link><div className="page-heading"><div><span className="eyebrow">Compartido con</span><h1>{link.recipient_label || 'Sin referencia'}</h1><p>{link.target_type === 'PRODUCT' ? link.product_slug?.toUpperCase() : 'Catálogo completo'}</p>{link.label && <p className="muted">Notas: {link.label}</p>}</div><button className="secondary-button" disabled={busy} onClick={toggle}>{link.status === 'ACTIVE' ? 'Desactivar' : 'Activar'}</button></div><div className="share-summary"><div><span>Visitas</span><strong>{link.total_opens ?? 0}</strong></div><div><span>Sesiones</span><strong>{link.total_sessions ?? 0}</strong></div><div><span>Última visita</span><strong>{link.last_seen_at ? new Date(link.last_seen_at).toLocaleString('es-CO') : '—'}</strong></div></div><section className="catalog-info"><span className="eyebrow">Productos consultados</span>{Object.entries(products).length ? Object.entries(products).map(([slug, count]) => <p key={slug}>Vio {slug.toUpperCase()} {count} {count === 1 ? 'vez' : 'veces'}.</p>) : <p className="muted">Aún no hay vistas de producto.</p>}</section><section className="catalog-info"><span className="eyebrow">Actividad reciente</span>{events.length ? events.slice(0, 30).map((event, index) => <p className="activity-line" key={`${event.occurred_at}-${index}`}><strong>{new Date(event.occurred_at).toLocaleString('es-CO')}</strong> {event.event_type === 'PRODUCT_VIEWED' ? `Vio ${event.product_slug?.toUpperCase()}` : event.event_type === 'LINK_OPENED' ? 'Entró por el enlace' : event.event_type === 'CATALOG_VIEWED' ? 'Entró al catálogo' : 'Inició una sesión'}</p>) : <p className="muted">Sin actividad registrada todavía.</p>}</section></>;
}
