export type NextActionInput = { role: string; currentStage: string; onboardingCompleted: boolean; milestones: string[]; pendingFollowups: number; openContactsWithoutNextStep: number };
export type NextAction = { id: string; actionType: string; title: string; description: string; reason: string; estimatedMinutes: number; primaryCTA: string; secondaryCTA?: string; destination: string; stage: string };

export function getNextAction(input: NextActionInput): NextAction {
  if (!input.onboardingCompleted) return { id:'complete-onboarding', actionType:'COMPLETE_ONBOARDING', title:'Termina de preparar tu espacio', description:'Cuéntanos lo esencial para darte un siguiente paso que tenga sentido para ti.', reason:'Tu onboarding aún está pendiente.', estimatedMinutes:3, primaryCTA:'Continuar onboarding', destination:'/onboarding', stage:input.currentStage };
  if (input.pendingFollowups > 0) return { id:'complete-followup', actionType:'COMPLETE_FOLLOWUP', title:'Completa tu seguimiento pendiente', description:'Cumple el próximo paso que ya habías acordado con una persona.', reason:'Tienes un seguimiento vencido o próximo.', estimatedMinutes:3, primaryCTA:'Ver seguimientos', destination:'/app/followups', stage:input.currentStage };
  if (input.role === 'ambassador' && input.currentStage === 'PRACTICE' && !input.milestones.includes('FIRST_PRACTICE')) return { id:'practice-first-conversation', actionType:'PRACTICE_FIRST_CONVERSATION', title:'Practica tu primera conversación', description:'Antes de hablar con alguien, mira cómo funciona una conversación sencilla y practica una vez.', reason:'La práctica es la evidencia que abre tu primera acción.', estimatedMinutes:3, primaryCTA:'Practicar ahora', destination:'/app/eli/practicar/primera-conversacion', stage:'PRACTICE' };
  if (input.role === 'ambassador' && !input.milestones.includes('FIRST_ACTION')) return { id:'take-first-action', actionType:'TAKE_FIRST_ACTION', title:'Ahora hazlo de verdad', description:'Elige una persona con quien exista una razón natural para conversar.', reason:'Ya tienes una práctica; el siguiente paso es una acción real.', estimatedMinutes:5, primaryCTA:'Preparar mi primera acción', destination:'/app/personas', stage:'FIRST_ACTION' };
  if (input.openContactsWithoutNextStep > 0) return { id:'define-next-step', actionType:'DEFINE_NEXT_STEP', title:'Define el siguiente paso', description:'Deja claro qué ocurrirá después en una conversación abierta.', reason:'Hay una persona sin siguiente paso registrado.', estimatedMinutes:2, primaryCTA:'Ver personas', destination:'/app/personas', stage:input.currentStage };
  return { id:'learn-next', actionType:'LEARN_NEXT', title:'Elige un recurso para avanzar', description:'Encuentra una práctica breve que te ayude con lo que estás haciendo ahora.', reason:'No hay bloqueos urgentes.', estimatedMinutes:5, primaryCTA:'Ver aprender', destination:'/app/aprender', stage:input.currentStage };
}
