'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { PASSWORD_POLICY } from '@/lib/auth/password-policy';
import { LogoutButton } from '@/components/auth/logout-button';

export default function ChangePasswordPage() {
  const router = useRouter(); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const longEnough = password.length >= PASSWORD_POLICY.minLength; const matches = password.length > 0 && password === confirmation; const valid = longEnough && matches;
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!valid || busy) return; setBusy(true); setError(''); const response = await fetch('/api/auth/change-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password, confirmPassword: confirmation }) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.error ?? 'No pudimos guardar la contraseña.'); setBusy(false); return; } router.push(result.nextPath); router.refresh(); }
  return <main className="auth-page"><section className="auth-card"><div className="auth-exit"><LogoutButton className="auth-logout" /></div><div className="auth-brand"><div className="brand-mark">E</div><div><strong>Elite Focus</strong></div></div><div className="eyebrow">Primer ingreso</div><h1>Crea tu contraseña<span style={{ color: 'var(--primary)' }}>.</span></h1><p className="subhead">Esta será la contraseña que usarás para entrar a Elite Focus.</p><div className="password-policy"><strong>Tu contraseña debe tener:</strong><span className={longEnough ? 'valid' : ''}>{longEnough ? '✓' : '○'} Al menos {PASSWORD_POLICY.minLength} caracteres</span><span className={matches ? 'valid' : ''}>{matches ? '✓' : '○'} Las contraseñas coinciden</span></div><form onSubmit={submit} className="auth-form"><label>Nueva contraseña<input name="password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /></label><label>Confirmar contraseña<input name="confirmPassword" type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="new-password" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary auth-submit" disabled={!valid || busy}>{busy ? 'GUARDANDO…' : 'GUARDAR CONTRASEÑA'}</button></form></section></main>;
}
