export type CatalogProduct = { slug: string; name: string; category: string; description: string; benefits: string[]; ingredients: string[]; usage: string[]; precautions: string[]; faqs: { question: string; answer: string }[]; image: string };
export const CATALOG_DATA_VERSION = '2026-10-02';

// Transitional versioned source copied from catalogozilis/data/products.ts.
// Future catalog/content work should promote this to a shared package.
export const catalogProducts: CatalogProduct[] = [
  { slug: 'ice', name: 'ICE', category: 'Antioxidantes', description: 'Una fórmula para acompañar rutinas de bienestar frente al cansancio y el desgaste diario.', benefits: ['Acompañamiento diario', 'Rutina sencilla', 'Enfoque antioxidante según la fuente aprobada'], ingredients: ['Resveratrol', 'Cúrcuma'], usage: ['Confirmar siempre presentación y preparación en la etiqueta oficial.'], precautions: ['No sustituye la etiqueta del producto ni la orientación profesional.'], faqs: [{ question: '¿Puedo usarlo todos los días?', answer: 'La indicación exacta debe confirmarse en la etiqueta oficial.' }], image: '/catalog/ice-product.png' },
  { slug: 'amalaki', name: 'AMALAKI', category: 'Bienestar diario', description: 'Una fórmula de apoyo constante para equilibrio y bienestar general.', benefits: ['Acompañamiento constante', 'Fórmula botánica según la fuente', 'Integración sencilla en la rutina'], ingredients: ['Amalaki', 'Tulsi', 'Jengibre', 'Inulina'], usage: ['Confirmar cantidad y preparación en la etiqueta oficial.'], precautions: ['Consultar la etiqueta oficial antes de usar.'], faqs: [{ question: '¿Qué información falta?', answer: 'La ficha nutricional y las indicaciones exactas deben validarse con documentación oficial.' }], image: '/catalog/amalaki-product.png' },
  { slug: 'b-fit', name: 'B-FIT', category: 'Metabolismo', description: 'Una fórmula presentada como apoyo para metabolismo, digestión y hábitos de bienestar.', benefits: ['Apoyo a una rutina metabólica', 'Formato en sobres', 'Acompañamiento digestivo según la referencia'], ingredients: ['Fórmula B-FIT'], usage: ['Confirmar siempre dosis y preparación contra la etiqueta oficial.'], precautions: ['No es un medicamento y no sustituye tratamiento médico, alimentación ni ejercicio.'], faqs: [{ question: '¿Cómo se presenta?', answer: 'La referencia pública muestra sobres individuales.' }], image: '/catalog/b-fit-product.png' },
  { slug: 'edge', name: 'EDGE', category: 'Energía y enfoque', description: 'Una opción presentada para acompañar enfoque y energía durante momentos de demanda.', benefits: ['Apoyo al enfoque', 'Energía para momentos de demanda', 'Formato stick pack'], ingredients: ['Fórmula EDGE'], usage: ['Confirmar cantidad y preparación en la etiqueta oficial.'], precautions: ['Consultar la etiqueta oficial sobre cafeína y otros estimulantes.'], faqs: [{ question: '¿Cuándo se suele tomar?', answer: 'El momento adecuado depende de la etiqueta y de la respuesta individual.' }], image: '/catalog/edge-product.png' },
  { slug: 'rise', name: 'RISE', category: 'Energía y enfoque', description: 'Café con una propuesta de energía más estable para acompañar el día.', benefits: ['Base de café arábica', 'Acompañamiento del enfoque', 'Rutina de café'], ingredients: ['Café arábica colombiano', 'Extracto de café verde', 'Amalaki'], usage: ['Confirmar preparación y cantidad en la etiqueta oficial.'], precautions: ['Revisar la cantidad de cafeína en la etiqueta.'], faqs: [{ question: '¿Es un café?', answer: 'La referencia lo presenta con café arábica colombiano como base.' }], image: '/catalog/rise-product.png' },
  { slug: 'ultra-vibe', name: 'ULTRA VIBE', category: 'Cannabinoides', description: 'Una fórmula de bienestar general enfocada en calma y equilibrio cotidiano.', benefits: ['Acompañamiento de la calma', 'Bienestar general', 'Rutina de equilibrio cotidiano'], ingredients: ['CBD', 'CBG', 'CBC'], usage: ['Confirmar cantidad y preparación en la etiqueta oficial.'], precautions: ['Consultar la etiqueta y la normativa aplicable antes de usar.'], faqs: [{ question: '¿Qué significa full spectrum?', answer: 'Es una descripción de fórmula que debe confirmarse con documentación oficial.' }], image: '/catalog/ultra-vibe-product.png' },
];
export function getCatalogProduct(slug: string) { return catalogProducts.find((product) => product.slug === slug); }
