'use client';

import { useState } from 'react';
import { AccessCard, type CreatedAccess } from './people-panel';

type Person = { id: string; first_name: string | null; last_name: string | null; email: string | null; zilis_id: string | null; username: string | null; experience_type: 'CLIENT_VIP' | 'AMBASSADOR'; must_change_password: boolean; onboarding_completed: boolean; current_stage: string | null; created_at: string | null; sponsor_id: string | null; advisor_id: string | null };
export function PersonDetailClient({ person, relationName, latestEvent, canReset }: { person: Person; relationName: string | null; latestEvent: { event_name: string; created_at: string } | null; canReset: boolean }) {
  const [confirm, setConfirm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [created, setCreated] = useState<CreatedAccess | null>(null);
  async function resetAccess() { setBusy(true); setError(''); const response = await fetch(`/api/people/${person.id}/reset-access`, { method: 'POST' }); const result = await response.json().catch(() => ({})); setBusy(false); setConfirm(false); if (!response.ok) { setError(result.message ?? 'No pudimos restablecer el acceso.'); return; } setCreated(result.person as CreatedAccess); }
  return <><div className="real-page__head"><div><div className="eyebrow">Persona acompañada</div><h1>{person.first_name ?? 'Sin nombre'} {person.last_name ?? ''}<span style={{ color: 'var(--primary)' }}>.</span></h1><p className="subhead">Detalle operativo para acompañar su siguiente paso.</p></div><span className="status-pill">{person.must_change_password ? 'PENDIENTE DE ACTIVACIÓN' : 'ACTIVO'}</span></div>{created && <AccessCard created={created} onDone={() => setCreated(null)} />} {error && <p className="form-error" role="alert">{error}</p>}<div className="person-detail-grid"><section className="panel"><h3>Identidad</h3><div className="admin-stat-list"><span><b>{person.experience_type === 'CLIENT_VIP' ? 'Cliente VIP' : 'Embajador'}</b> experiencia</span><span><b>{person.zilis_id ?? person.username ?? '—'}</b> ID Zilis</span><span>{person.email ?? 'Sin correo registrado'}</span></div></section><section className="panel"><h3>Relación</h3><div className="admin-stat-list"><span><b>{person.experience_type === 'CLIENT_VIP' ? 'Advisor' : 'Sponsor'}</b></span><span>{relationName ?? 'Relación no disponible'}</span></div></section><section className="panel"><h3>Activación</h3><div className="admin-stat-list"><span><b>{person.onboarding_completed ? 'Completado' : 'Pendiente'}</b> onboarding</span><span><b>{person.current_stage ?? 'ORIENTATION'}</b> etapa actual</span><span>{person.created_at ? new Date(person.created_at).toLocaleDateString('es-ES') : '—'} alta</span></div></section><section className="panel"><h3>Última señal</h3><div className="admin-stat-list"><span>{latestEvent?.event_name ?? 'Todavía no hay actividad registrada.'}</span>{latestEvent?.created_at && <small className="admin-muted">{new Date(latestEvent.created_at).toLocaleString('es-ES')}</small>}</div></section></div>{canReset && <section className="panel detail-action-panel"><div><h3>Acceso</h3><p className="admin-muted">La contraseña anterior nunca se recupera. Genera una nueva solo si es necesario.</p></div><button className="primary" onClick={() => setConfirm(true)}>Restablecer acceso</button></section>}{confirm && <div className="confirm-backdrop"><div className="confirm-card" role="dialog" aria-modal="true"><div className="eyebrow">Acceso</div><h2>Restablecer acceso</h2><p>Se generará una nueva contraseña temporal. La contraseña anterior dejará de funcionar.</p><div className="confirm-actions"><button className="secondary" onClick={() => setConfirm(false)}>Cancelar</button><button className="primary" disabled={busy} onClick={resetAccess}>{busy ? 'Generando…' : 'Generar nueva contraseña'}</button></div></div></div>}</>;
}
