'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { AddPersonDialog, AccessCard, type CreatedAccess } from './people-panel';

type TeamPerson = { id: string; first_name: string | null; last_name: string | null; zilis_id: string | null; username: string | null; experience_type: 'CLIENT_VIP' | 'AMBASSADOR'; onboarding_completed: boolean; current_stage: string | null; created_at: string | null; sponsor_id: string | null; advisor_id: string | null; status: string };
export function TeamClient({ initialList, initialLatest, ambassadors: initialAmbassadors, clients: initialClients }: { initialList: TeamPerson[]; initialLatest: Array<[string, { event_name: string; created_at: string }]>; ambassadors: number; clients: number }) {
  const [list, setList] = useState(initialList); const [created, setCreated] = useState<CreatedAccess | null>(null); const [open, setOpen] = useState(false); const router = useRouter(); const latest = new Map(initialLatest);
  function onCreated(access: CreatedAccess) { setCreated(access); setOpen(false); setList((current) => [{ id: access.id, first_name: access.firstName, last_name: access.lastName, zilis_id: access.username, username: access.username, experience_type: access.experienceType, onboarding_completed: false, current_stage: 'ORIENTATION', created_at: new Date().toISOString(), sponsor_id: access.experienceType === 'AMBASSADOR' ? 'current' : null, advisor_id: access.experienceType === 'CLIENT_VIP' ? 'current' : null, status: 'PENDIENTE' }, ...current]); router.refresh(); }
  const ambassadors = list.filter((person) => person.experience_type === 'AMBASSADOR').length || initialAmbassadors; const clients = list.filter((person) => person.experience_type === 'CLIENT_VIP').length || initialClients;
  return <main className="real-page team-page"><div className="team-heading"><div><div className="eyebrow">Crecimiento con contexto</div><h1>Mi equipo<span style={{ color: 'var(--primary)' }}>.</span></h1><p className="subhead team-intro">Acompaña a las personas que están creciendo contigo.</p></div><button className="primary" onClick={() => setOpen((value) => !value)}>+ AGREGAR PERSONA</button></div>{open && <AddPersonDialog onCreated={onCreated} onClose={() => setOpen(false)} />}{created && <AccessCard created={created} onDone={() => setCreated(null)} />}<div className="team-summary"><div className="team-summary__card"><b>{list.length}</b><span>Personas</span></div><div className="team-summary__card"><b>{ambassadors}</b><span>Embajadores</span></div><div className="team-summary__card"><b>{clients}</b><span>Clientes VIP</span></div></div><section className="team-attention panel"><div className="panel-head"><h3>Necesitan atención</h3><span className="admin-muted">Señales reales</span></div><div className="attention-list">{list.filter((person) => !person.onboarding_completed || !latest.has(person.id)).length === 0 ? <p className="admin-muted">No hay pendientes urgentes.</p> : list.filter((person) => !person.onboarding_completed || !latest.has(person.id)).slice(0, 4).map((person) => <Link href={`/app/personas/${person.id}`} className="attention-row" key={person.id}><span>{person.first_name} {person.last_name}</span><small>{!person.onboarding_completed ? 'Onboarding pendiente' : 'Sin actividad registrada'} →</small></Link>)}</div></section><section className="team-list"><div className="panel-head"><h3>Tu equipo</h3><span className="admin-count">{list.length}</span></div>{list.map((person) => <Link href={`/app/personas/${person.id}`} className="panel team-person-card" key={person.id}><div className="admin-avatar">{(person.first_name ?? 'EF').slice(0, 2).toUpperCase()}</div><div><strong>{person.first_name} {person.last_name}</strong><small>{person.experience_type === 'CLIENT_VIP' ? 'Cliente VIP' : 'Embajador'} · {person.current_stage ?? 'ORIENTATION'}</small></div><div className="team-person-card__signal"><span>{latest.get(person.id)?.event_name ?? 'Sin actividad'}</span><small>{latest.get(person.id)?.created_at ? new Date(latest.get(person.id)!.created_at).toLocaleDateString('es-ES') : '—'}</small></div><b className="admin-user-card__arrow">→</b></Link>)}</section></main>;
}
