'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { LogoutButton } from '@/components/auth/logout-button';

type FormState = { role: 'customer' | 'ambassador'; primaryGoal: string; experienceLevel: string; startingPreference: string; firstName: string; lastName: string; acceptedRules: boolean };
const ambassadorSteps = [{ key: 'primaryGoal', title: '¿Qué quieres conseguir primero?', options: ['Conocer mejor los productos', 'Conseguir mi primer cliente', 'Empezar a mover mi negocio', 'Todavía no estoy seguro'] }, { key: 'experienceLevel', title: '¿Has vendido antes?', options: ['Nunca', 'Un poco', 'Sí, tengo experiencia'] }, { key: 'startingPreference', title: '¿Cómo prefieres comenzar?', options: ['Quiero empezar haciendo', 'Quiero entender primero lo esencial'] }];

export function OnboardingWizard({ experienceType, firstName, lastName }: { experienceType: 'CLIENT_VIP' | 'AMBASSADOR'; firstName: string; lastName: string }) {
  const router = useRouter(); const [data, setData] = useState<FormState>({ role: experienceType === 'CLIENT_VIP' ? 'customer' : 'ambassador', primaryGoal: '', experienceLevel: '', startingPreference: '', firstName, lastName, acceptedRules: false }); const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const steps = data.role === 'customer' ? [] : ambassadorSteps; const total = steps.length + 1; const current = step < steps.length ? steps[step].key : 'culture';
  function choose(key: string, value: string) { setData((prev) => ({ ...prev, [key]: value })); setError(''); }
  async function next() { if (step < steps.length && !data[current as keyof FormState]) { setError('Elige una opción para continuar.'); return; } if (step < steps.length - 1) { setStep(step + 1); return; } if (step === steps.length - 1) { setStep(steps.length); return; } if (!data.acceptedRules) { setError('Necesitamos que aceptes estas reglas para continuar.'); return; } setBusy(true); const response = await fetch('/api/auth/onboarding', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.error ?? 'No pudimos guardar tu onboarding. Inténtalo de nuevo.'); setBusy(false); return; } router.push(result.redirect ?? '/app'); router.refresh(); }
  return <main className="onboarding-page"><section className="onboarding-card"><div className="auth-exit"><LogoutButton className="auth-logout" /></div><div className="onboarding-top"><span className="eyebrow">Tu comienzo · {Math.min(step + 1, total)} de {total}</span><span className="onboarding-progress"><i style={{ width: `${((step + 1) / total) * 100}%` }} /></span></div>{step < steps.length ? <><h1>{steps[step].title}<span style={{ color: 'var(--primary)' }}>.</span></h1><p className="subhead">Cada respuesta define un punto de partida más claro.</p><div className="choice-list">{steps[step].options.map((option) => <Choice key={option} title={option} selected={data[current as keyof FormState] === option} onClick={() => choose(current, option)} />)}</div></> : <><h1>Así trabajamos en Elite Focus<span style={{ color: 'var(--primary)' }}>.</span></h1><p className="subhead">Respeto, amor, servicio e integridad acompañan cada acción.</p><div className="rules-list"><span>No diagnosticar ni inventar información.</span><span>No prometer resultados ni ingresos.</span><span>Respetar privacidad y pedir permiso antes de enviar información comercial.</span><span>No hacer spam.</span></div><label className="consent"><input type="checkbox" checked={data.acceptedRules} onChange={(event) => setData({ ...data, acceptedRules: event.target.checked })} /> Acepto estas reglas esenciales <small>Versión 1.0</small></label></>}{error && <p className="form-error" role="alert">{error}</p>}<div className="onboarding-actions">{step > 0 && <button className="public-button public-button--secondary" onClick={() => setStep(step - 1)}>Atrás</button>}<button className="primary" disabled={busy} onClick={next}>{busy ? 'GUARDANDO…' : step === steps.length ? 'VER MI SIGUIENTE PASO' : 'CONTINUAR →'}</button></div></section></main>;
}
function Choice({ title, selected, onClick }: { title: string; selected: boolean; onClick: () => void }) { return <button type="button" className={`choice ${selected ? 'choice--selected' : ''}`} onClick={onClick}><span><b>{title}</b></span><i aria-hidden="true">{selected ? '✓' : ''}</i></button>; }
